config/routes.rb
Anything::Application.routes.draw do

  resources :status_updates do
    member do
      post :upvote
      post :downvote
    end
  end


  get "wall/index"

  resources :groups do 
  	member do 
  		post :join
  		post :leave
  	end
  end


  resources :user_profiles


  authenticated :user do
    
    root :to => 'wall#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users do 
    member do
      get :following
      get :followers
end
end 


resources :relationships, :only => [:create, :destroy]

end

app/models/status_update.rb
class StatusUpdate < ActiveRecord::Base
  belongs_to :user
  attr_accessible :content

  acts_as_votable
  default_scope :order => 'created_at DESC'
end

app/controllers/status_updates_controller.rb
class StatusUpdatesController < ApplicationController

  def upvote
    @status_update = StatusUpdate.find(params[:id])
    @status_update.liked_by current_user
    redirect_to :back
  end

   def downvote
    @status_update = StatusUpdate.find(params[:id])
    @status_update.disliked_by current_user
    redirect_to :back
  end
  # GET /status_updates
  # GET /status_updates.json
  def index
    @status_updates = StatusUpdate.all


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @status_updates }
    end
  end

  # GET /status_updates/1
  # GET /status_updates/1.json
  def show
    @status_update = StatusUpdate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @status_update }
    end
  end

  # GET /status_updates/new
  # GET /status_updates/new.json
  def new
    @status_update = StatusUpdate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @status_update }
    end
  end

  # GET /status_updates/1/edit
  def edit
    @status_update = StatusUpdate.find(params[:id])
  end

  # POST /status_updates
  # POST /status_updates.json
  def create
    @status_update = StatusUpdate.new(params[:status_update])
    @status_update.user = current_user

    respond_to do |format|
      if @status_update.save
        format.html { redirect_to root_path, notice: 'Status update was successfully created.' }
        format.json { render json: @status_update, status: :created, location: @status_update }
      else
        format.html { render action: "new" }
        format.json { render json: @status_update.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /status_updates/1
  # PUT /status_updates/1.json

  def update
    @status_update = StatusUpdate.find(params[:id])

    respond_to do |format|
      if @status_update.update_attributes(params[:status_update])
        format.html { redirect_to @status_update, notice: 'Status update was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @status_update.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /status_updates/1
  # DELETE /status_updates/1.json
  def destroy
    @status_update = StatusUpdate.find(params[:id])
    @status_update.destroy

    respond_to do |format|
      format.html { redirect_to status_updates_url }
      format.json { head :no_content }

    end
  end
end

app/helpers/status_updates_helper.rb
module StatusUpdatesHelper
end

app/views/status_updates/_form.html.erb
<%= simple_form_for(@status_update) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :content, :label => "Share" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/status_updates/edit.html.erb
<h1>Editing status_update</h1>

<%= render 'form' %>

<%= link_to 'Show', @status_update %> |
<%= link_to 'Back', status_updates_path %>

app/views/status_updates/index.html.erb
<h1>Listing status_updates</h1>

<table class = "table">
  <tr>
    <th>Content</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @status_updates.each do |status_update| %>
  <tr>
    <td><%= status_update.content %></td>
    <td><%= status_update.user.name %></td>
      <td><%= status_update.created_at.strftime("%e, %b, %Y") %></td>
    <td><%= link_to 'Show', status_update %></td>
    <td><%= link_to 'Edit', edit_status_update_path(status_update) %></td>
    <td><%= link_to 'Destroy', status_update, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  
  <div class="row">
    <div class="span4">
      <p><%= status_update.content %></p>
      <br>
      <% if !current_user.liked?(status_update) %>
      <%= link_to 'Like', upvote_status_update_path(status_update), :method => :post, :class => 'btn' %>
       <% else %>
      <%= link_to 'Unlike', downvote_status_update_path(status_update), :method => :post, :class => 'btn' %>
  <% end %>
    <br>
    Likes: <%= status_update.votes.size %>
  </tr>
  </div>
</div>
<% end %>
</table>

<br />



<%= link_to 'New Status update', new_status_update_path %>

app/views/status_updates/new.html.erb
<h1>New status_update</h1>

<%= render 'form' %>

<%= link_to 'Back', status_updates_path %>

app/views/status_updates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @status_update.content %>

  </p>"

<p>
  <b>User:</b>
  <%= @status_update.user %>
</p>


<%= link_to 'Edit', edit_status_update_path(@status_update) %> |
<%= link_to 'Back', status_updates_path %>