config/routes.rb
Anything::Application.routes.draw do

  resources :status_updates do
    member do
      post :upvote
      post :downvote
    end
  end


  get "wall/index"

  resources :groups do 
  	member do 
  		post :join
  		post :leave
  	end
  end


  resources :user_profiles


  authenticated :user do
    
    root :to => 'wall#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users do 
    member do
      get :following
      get :followers
end
end 


resources :relationships, :only => [:create, :destroy]

end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :description, :name, :owner

  has_many :user_groups
  has_many :users, :through => :user_groups

  def in_group?(user)
  	self.users.include?(users)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
 
  def join
    @group = Group.find(params[:id])
    @user = User.find(params[:user])

    if not @user.is_member?(@group)
      @group.users << @user
      flash[:notice] = "You have been added to the group"
    else
      flash[:error] = "You have already been added to the group"

    end
      redirect_to @group
  end

  def leave
    @user = User.find(params[:user])
    @group = User.find(params[:id])

    if @user.is_member?(@group)
      logger.info "Removing user from group #{@group.id}"
      @user.groups.delete(@group)
      flash[:notice] = "You have left the group"
    end
    redirect_to @group
  end

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])
    @user = User.find(@group.owner)
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])
    @group.owner = current_user.id
    @group.users << current_user

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
	
end

app/views/groups/_form.html.erb
<%= simple_form_for(@group) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, :input_html => { :class => "span4" } %> 
    <%= f.input :description, :input_html => { :class => "span4", :rows => 3 } %>  
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Listing groups</h1>

<table  class = "table">
  <tr>
    <th>Name</th>
    <th>Owner</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @groups.each do |group| %>

  <tr>
    <td><%= group.name %></td>
    <td><%= group.owner %></td>
    <td><%= group.description %></td>
    <td><%= link_to 'Show', group %></td>
    <td><%= link_to 'Edit', edit_group_path(group) %></td>
    <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @group.name %></h1>

<p>
  <b>Owner:</b>
  <%= @user.name %>
</p>

<p>
  <b>Description:</b>
  <%= @group.description %>
</p>

<% if user_signed_in? %>
	<% if !current_user.is_member?(@group) %>
		<%= link_to "Join this group", join_group_path(:user => current_user), :method => :post, :class => 'btn btn-primary' %>

	<% else %>
		<%= link_to "Leave this group", leave_group_path(:user => current_user), :method => :post, :class => 'btn btn-warning' %>
	<% end %>
<% end %>


<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>