config/routes.rb
Anything::Application.routes.draw do

  resources :status_updates do
    member do
      post :upvote
      post :downvote
    end
  end


  get "wall/index"

  resources :groups do 
  	member do 
  		post :join
  		post :leave
  	end
  end


  resources :user_profiles


  authenticated :user do
    
    root :to => 'wall#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users do 
    member do
      get :following
      get :followers
end
end 


resources :relationships, :only => [:create, :destroy]

end

app/models/user_profile.rb
class UserProfile < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader

  belongs_to :user
  attr_accessible :about, :facebook, :github, :hobbies, :user_profile, :avatar, :string
end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  # GET /user_profiles
  # GET /user_profiles.json
  def index
    @user_profiles = UserProfile.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_profiles }
    end
  end

  # GET /user_profiles/1
  # GET /user_profiles/1.json
  def show
    @user_profile = UserProfile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_profile }
    end
  end

  # GET /user_profiles/new
  # GET /user_profiles/new.json
  def new
    @user_profile = UserProfile.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_profile }
    end
  end

  # GET /user_profiles/1/edit
  def edit
    @user_profile = UserProfile.find(params[:id])
  end

  # POST /user_profiles
  # POST /user_profiles.json
  def create
    @user_profile = UserProfile.new(params[:user_profile])
    @user_profile.user = current_user
    respond_to do |format|
      if @user_profile.save
        format.html { redirect_to @user_profile, notice: 'User profile was successfully created.' }
        format.json { render json: @user_profile, status: :created, location: @user_profile }
      else
        format.html { render action: "new" }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_profiles/1
  # PUT /user_profiles/1.json
  def update
    @user_profile = UserProfile.find(params[:id])

    respond_to do |format|
      if @user_profile.update_attributes(params[:user_profile])
        format.html { redirect_to @user_profile, notice: 'User profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_profiles/1
  # DELETE /user_profiles/1.json
  def destroy
    @user_profile = UserProfile.find(params[:id])
    @user_profile.destroy

    respond_to do |format|
      format.html { redirect_to user_profiles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/views/user_profiles/_form.html.erb
<%= simple_form_for @user_profile, {:multipart => true} do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :about %>
    <%= f.input :hobbies %>
    <%= f.input :github %>
    <%= f.input :facebook %>
    <%= f.input :avatar, :as => :file %>
    <%= f.submit 'Create Profile', :class => 'btn btn-success' %>
  
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/user_profiles/edit.html.erb
<h1>Editing user_profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_profile %> |
<%= link_to 'Back', user_profiles_path %>

app/views/user_profiles/index.html.erb
<h1>Listing user_profiles</h1>

<table class="table">
  <tr>
    <th>User</th>
    <th>About</th>
    <th>Hobbies</th>
    <!--<th>Github</th>
    <th>Facebook</th>-->
    
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_profiles.each do |user_profile| %>
  <tr>
    <td><%= link_to user_profile.user.name, user_profile %></td>
    <td><%= user_profile.about %></td>
    <td><%= user_profile.hobbies %></td>
    <!--<td><%= user_profile.github %></td>
    <td><%= user_profile.facebook %></td>-->
    <td><%= user_profile.user %></td>
   <!-- <td><%= link_to 'Show', user_profile %></td> -->
    <td><%= link_to 'Edit', edit_user_profile_path(user_profile) %></td>
    <td><%= link_to 'Destroy', user_profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User profile', new_user_profile_path %>

app/views/user_profiles/new.html.erb
<h1>New user_profile</h1>

<%= render 'form' %>

<%= link_to 'Back', user_profiles_path %>

app/views/user_profiles/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag(@user_profile.avatar_url) if @user_profile.avatar? %>

<p>
  <b>About:</b>
  <%= truncate @user_profile.about %>
</p>

<p>
  <b>Hobbies:</b>
  <%= truncate @user_profile.hobbies %>
</p>

<p>
  <b>Github:</b>
  <%= @user_profile.github %>
</p>

<p>
  <b>Facebook:</b>
  <%= @user_profile.facebook %>
</p>

<p>
  <b>User:</b>
  <%= link_to @user_profile.user.name, @user_profile.user %>
</p>


<%= link_to 'Edit', edit_user_profile_path(@user_profile) %> |
<%= link_to 'Back', user_profiles_path %>